### ISSUE TITLE
Fix Travis Build error

### ISSUE THREAD

**Issue by co-robo** [coala/coala-emacs#22] opened 2017-11-07 08:02 UTC
Read Travis CI log and fix it.
Opened by @aashutoshrathi at [Gitter](https://gitter.im/coala/coala?at=5a0168a55a1758ed0f9a3f6a)

**Comment by jayvdb** [comment] 2017-11-07 08:04
Please create good issues with links to travis logs, etc.

**Comment by aashutoshrathi** [comment] 2017-11-07 08:06
Check Travis log here: https://travis-ci.org/coala/coala-emacs

**Comment by jayvdb** [comment] 2017-11-07 08:07
that is not a good link.  precise links, with the relevant snippets copied here .

**Comment by 9r0x** [comment] 2017-11-07 08:19
I am working on pr #20 and maybe I can fix it

**Comment by jayvdb** [comment] 2017-11-07 08:22
https://travis-ci.org/coala/coala-emacs/builds/255744435 is a build that failed.
That was the push for https://github.com/coala/coala-emacs/pull/17 , which did pass during the PR

**Comment by 9r0x** [comment] 2017-11-07 10:34
@jayvdb @aashutoshrathi Fixed now, it was a problem caused by upstream repo https://github.com/melpa/melpa/issues/3833

**Comment by jayvdb** [comment] 2018-06-05 11:18
Thanks @Grox-Ni for investigating.

**Closed as completed by jayvdb** 2018-06-05 11:18 UTC
Labels: difficulty/medium
